builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - files:
      - LICENSE
      - cpthook.yml.example

checksum:
  name_template: "checksums.txt"
