---
language: go
go:
  - "1.14"

services:
  - docker

env:
  global:
    - IMAGE="fleaz/cpthook"
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - cp cpthook.yml.example cpthook.yml
  - go test ./... -v
  - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o CptHook
  - docker build -f Dockerfile -t $IMAGE .

deploy:
  # Build production Docker container
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh stable
    on:
      branch: main
  # Build tagged Docker container
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh $TRAVIS_TAG
    on:
      tags: true
      branch: main
  # Build development Docker container
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh development
    on:
      branch: development
  # Build release files with goreleaser
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
