name: goreleaser

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: cp cpthook_example.yml cpthook.yml
      - run: go build
      - name: Test
        run: go test -v ./...